### ISSUE TITLE
关于元任务训练模式和task重复

### ISSUE THREAD

**Issue by dota2mhxy** [fyancy/MetaFD#5]
你好,谢谢你之前的回信,很有帮助,又有新的问题麻烦你.原型网络训练代码是这样
![image](https://user-images.githubusercontent.com/64951554/162436824-3168cda8-71e1-457b-be52-d3f6f78fc31f.png)
       我有点不明白元学习的训练模式,想请教你.CNN的训练就是一个epoch中分多个batch,batch之间的数据互不相同.但是每个epoch的数据都是一样的,是重复的训练.到了元任务的模式,我看是分成epoch和eposide,其他论文也是这么写的,但是我看代码,他是根据一个个task来训练模型的,    train_tasks.sample()  生成的样本是随机的.那么是否不单eposide之间的数据不一样,其实不同epoch训练数据也不相同?那么分成epoch和eposide有什么意义,就是单纯规定一个合适的周期来看训练的精度吗?
       我看到在训练和测试时,遍历task是不同的,训练时是这样  task = train_tasks.sample() ,测试时
   for i, batch in enumerate(train_tasks)
       但是根据我的测试 train_tasks.sample() 可能会返回2个数据相同的task,后面那种遍历没有这个情况.同时如果**2个task的数据完全相同.我的意思是如果task的data的tensor的数据完全一样**,那么是否认为这2个task就是重复的,对提高模型精度就没有效果?还有就是task的重复的可能概率是如何估计,如果重复率过高是否对训练有负面影响?期盼你能简答我的疑惑,不谢感谢!

**Comment by dota2mhxy** [comment]
@fyancy

**Comment by fyancy** [comment]
- 问题1：episode与epoch
- [ ] epoch和episode是元学习训练中的两个概念，epoch的概念与普通的训练中的概念一致，在一个epoch内遍历完所有task；episode你也可以看成是一个batch，但是每个batch内的task数据条件分布是不一样的，P(Y|X)，比如同样一个样本在这个task里面的label可能是0，在下一个task的label就是2或者3这样子，之所以有这种设置，是让模型不对具体的数据记忆固定的映射关系，而是通过几个少量的训练task，就可以确定这种映射(或者理解为学习到一种新的映射关系)，这就是快速适应fast to adapt的能力。在prototypical network这一类度量元学习网络，没有内循环的步骤，因此直接在一个episode里面进行一次参数的update，与普通CNN的训练其实相差不大，只是在训练阶段进行了task的情景式训练。在这个意义上，您的理解是对的，episodes其实与epoch的界限模糊，在CV领域大多使用iteration（近似于episodes）来统一两个概念，不分彼此。

- 问题2：训练、测试的task差异
- [ ] 在训练时，我需要让有限的数据集(我只使用了CWRU这一个数据集)中的有限的训练数据发挥较大的作用，产生随机性、随机组合产生不同task等，因此我用了10000*30 (protoNet) 来进行训练，你可以直接舍弃epoch，使用300，000这个总的训练轮数。在测试时，应当遵循对所有模型都使用相同的设置，把所有任务遍历完就行。当然，你需要固定随机种子，不然每次测试的结果有差异(产生的task不同)。你可以采取更准确的做法，比如特意划分出产生prototype的数据，其他数据都作为test data，且产生不相交的、无重复的task。(不知道是否可以在TaskDataset()里面定义)

**Comment by dota2mhxy** [comment]
好的,谢谢你的回复.
